name: gq
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_osm_plugin: ^0.60.5
  osm_flutter_hooks: ^1.4.0
  flutter_spinkit: ^5.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: 'i_assets/logo.png'

